let data = [
    {
        id : 0,
        title : "상호",
        standardVal : "자동세팅",
        type : "text",
        group: "기업정보",
    },
    {
        id : 1,
        title : "사업자등록번호",
        standardVal : "자동세팅",
        type : "text",
        group: "기업정보",
    },
    {
        id : 2,
        title : "업종",
        standardVal : "자동세팅",
        type : "text",
        group: "기업정보",
    },
    {
        id : 3,
        title : "직원수",
        standardVal : "고객입력",
        type : "text",
        group: "기업정보",
    },
    {
        id : 4,
        title : "제무제표 보유",
        standardVal : "자동세팅",
        type : "text",
        group: "기업정보",
    },
    {
        id : 5,
        title : "과세유형",
        standardVal : "자동세팅",
        type : "text",
        group: "기업정보",
    },
    {
        id : 6,
        title : "매출액",
        standardVal : "고객입력",
        val1 : "전기",
        val2 : "당기",
        type : "text",
        group: "기업정보",
    },
    {
        id : 7,
        title : "스마트스토어 주소",
        standardVal : "자동세팅",
        type : "text",
        group: "기업정보",
    },
    {
        id : 8,
        title : "대표자명",
        standardVal : "자동세팅",
        type : "text",
        group: "대표자정보",
    },
    {
        id : 9,
        title : "주민번호",
        standardVal : "자동세팅",
        type : "text",
        group: "대표자정보",
    },
    {
        id : 10,
        title : "경영형태",
        standardVal : "자동세팅",
        type : "text",
        group: "대표자정보",
    },
    {
        id :11,
        title : "주된 경영자",
        standardVal : "자동세팅",
        type : "text",
        group: "대표자정보",
    },
    {
        id : 12,
        title : "사업장 주소",
        standardVal : "주소찾기",
        type : "text",
        group: "주소정보",
    },
    {
        id : 13,
        title : "주사업장 여부",
        standardVal : "자동세팅",
        type : "text",
        group: "주소정보",
    },
    {
        id : 14,
        title : "소유자",
        standardVal : "자동세팅",
        type : "text",
        group: "주소정보",
    },
    {
        id : 15,
        title : "소유형태",
        standardVal : "자동세팅",
        type : "text",
        group: "주소정보",
    },
    {
        id : 16,
        title : "권리침해(최근 1년)",
        standardVal : "자동세팅",
        type : "text",
        group: "주소정보",
    },
    {
        id : 17,
        title : "거주지 주소",
        standardVal : "주소찾기",
        type : "text",
        group: "주소정보",
    },
    {
        id : 18,
        title : "현거주지 여부",
        standardVal : "자동세팅",
        type : "text",
        group: "주소정보",
    },
    {
        id : 19,
        title : "소유자",
        standardVal : "자동세팅",
        type : "text",
        group: "주소정보",
    },
    {
        id : 20,
        title : "소유형태",
        standardVal : "자동세팅",
        type : "text",
        group: "주소정보",
    },
    {
        id : 21,
        title : "권리침해(최근 1년)",
        standardVal : "자동세팅",
        type : "text",
        group: "주소정보",
    },
    {
        id : 22,
        title : "기타부동산 보유 여부",
        standardVal : "고객입력",
        type : "text",
        group: "기타정보",
    },
    {
        id : 23,
        title : "소유자",
        standardVal : "고객입력",
        type : "text",
        group: "기타정보",
    },
    {
        id : 24,
        title : "부동산 주소",
        standardVal : "주소찾기",
        type : "text",
        group: "기타정보",
    },
    {
        id : 25,
        title : "대출희망금액",
        standardVal : "자동세팅",
        type : "text",
        group: "대출정보",
    },
    {
        id : 26,
        title : "보증신청금액",
        standardVal : "자동세팅",
        type : "text",
        group: "대출정보",
    },
    {
        id : 27,
        title : "대출은행",
        standardVal : "자동세팅",
        type : "text",
        group: "은행",
    },
    {
        id : 28,
        title : "지점명",
        standardVal : "자동세팅",
        type : "text",
        group: "은행",
    },
    
];

export default data;